### ISSUE TITLE
No longer working (no uber Request)

### ISSUE THREAD

**Issue by Euzebius** [eddiez9/sans-ondemand-download#9]
Sans changed the working mode, so no longer uberRequest involved.
Still can access manually to webm files in network tab but it's taking long.
Any chance the script can be adapted for the new version ?

**Comment by eddiez9** [comment]
Gonna need more information than this to troubleshoot as I still see the request in all the courses I can access.

Can you send a screen recording of what you're doing to hello@eddiez.me

**Comment by Euzebius** [comment]
When I access my course, URL looks like https://olt-players.sans.org/production/latest/ProxGwtApp.htm?tid=....

No trace of uberRequest in chrome , I have a request to script.json but I'm not sure the file is relevant

**Comment by eddiez9** [comment]
As I said, all the courses I have access to still have the uber request as per instructions.

You can:
1. Send me a screen recording of what you're doing so I can see what the issue is
2. Give me your account so I can troubleshoot
3. Write a fix and submit a pull request

**Comment by Euzebius** [comment]
Looks like a bug with my chrome (which is up to date) , I managed to catch the request with burp.
Sorry for inconvenience ...

**Comment by eddiez9** [comment]
Did you open the F12 network tab before browsing to the page where you can watch videos?

The default behaviour for Chrome is that it won't start recording until you open up the developer tools for the first time for that tab. So you if you browsed to it first and then pressed F12 it won't show up because it wasn't recording.
